FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY TestRabbitClient.csproj .
RUN dotnet restore .

# copy everything else and build app
COPY Channel/ ./Channel
COPY Dispatch/ ./Dispatch
COPY TestRabbitClient.Tests/ ./TestRabbitClient.Tests

RUN dotnet build .
CMD dotnet test
